name: Document Expiration Check

on:
  push:
    branches: [ $default-branch,  'best-before']
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check markdown docs expiration
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        run: node ./best-before-document-github-action/index.js
